export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_CANVAS = 'LOAD_CANVAS';
export const REMOVE_CANVAS = 'REMOVE_CANVAS';
export const SET_CURRENT_CANVAS = 'SET_CURRENT_CANVAS';
export const CLEAR_CURRENT_CANVAS = 'CLEAR_CURRENT_CANVAS';

export const HIDE_NAVIGATION = 'HIDE_NAVIGATION';
export const SHOW_NAVIGATION = 'SHOW_NAVIGATION';
